let Images = {
    // magnumLogo: require('../images/Magnum_logo.png'),
    home: require('../images/ic_home.png'),
    search: require('../images/ic_search.png'),
    account: require('../images/ic_account.png'),
    magnumLogoBlack: require('../images/magnum_logo_black.png'),
    backbuttonIcon: require('../images/ic_backbutton_top.png'),
    eyeVisible: require('../images/eye_visible.png'),
    eyeInvisible: require('../images/eye_invisible.png'),
    //NEW
    ic_drawer: require('../images/ic_drawer.png'),
    top_bg: require('../images/top_bg.png'),
    jmvi_logo: require('../images/jmvi_logo.png'),
    featured: require('../images/featured.png'),
    ic_powerd_by: require('../images/ic_powerd_by.png'),
    sale: require('../images/sale.png'),
    rent: require('../images/rent.png'),
    bid: require('../images/bid.png'),
    favourite: require('../images/favourite.png'),
    find_an_agent: require('../images/find_an_agent.png'),
    mortgage_calculator: require('../images/mortgage_calculator.png'),
    mortgage_financing: require('../images/mortgage_financing.png'),
    property_lawyers: require('../images/property_lawyers.png'),
    location: require('../images/location.png'),
    about_us: require('../images/about_us.png'),
    contact_us: require('../images/contact_us.png'),
    tnc: require('../images/tnc.png'),
    user: require('../images/user.png'),
    register: require('../images/register.png'),
    agent_placeholder: require('../images/agent_placeholder.jpg'),
    mail: require('../images/mail.png'),
    call: require('../images/call.png'),
    bed: require('../images/bed.png'),
    bath: require('../images/bath.png'),
    ic_drop_down_arrow: require('../images/ic_drop_down_arrow.png'),
    cancel: require('../images/cancel.png'),
    ic_fb: require('../images/ic_fb.png'),
    ic_twitter: require('../images/ic_twitter.png'),
    phone: require('../images/phone.png'),
    pin: require('../images/pin.png'),
    fill_circle: require('../images/fill_circle.png'),
    circle: require('../images/circle.png'),
    dorpdown_fill: require('../images/dorpdown_fill.png'),
    logout: require('../images/logout.png'),
    trash: require('../images/trash.png'),
    ic_fill_heart: require('../images/ic_fill_heart.png'),
    ic_heart: require('../images/ic_heart.png'),
    info: require('../images/info.png'),
    close: require('../images/ic_close_input.png'),

}
export default Images
